### ISSUE TITLE
beta release

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [hparadiz/divergence#1]
i have download in my hosting and test you system))

**Comment by hparadiz** [comment]
Спасибо! Если у вас есть вопросы, я говорю по-русски.

Я кодирую модульные тесты сичас.

Я рекомендую вам проверить https://github.com/hparadiz/technexus, чтобы увидеть рабочий сайт.

**Comment by Pomazan-Bogdan** [comment]
Я не умею пользоваться сборщиками сайтов.
Можете добавить скриншотов?

**Comment by Pomazan-Bogdan** [comment]
admin panel end builder
